// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbddgjxxthujmpijivto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiZGRnanh4dGh1am1waWppdnRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTQ1NTgsImV4cCI6MjA3Mzk3MDU1OH0.QT6Dc3qrDUBWPQCYYjooJVM6QeDNa9Kcm3s6Zmibqas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});